version: '3.8'

services:
  backend:
    build: ./back-end
    ports:
      - "8000:8000"
    volumes:
      - ./back-end:/app
    environment:
      - DB_URI=sqlite:///./insight.db

  frontend:
    build: ./front-end/geobrasil
    ports:
      - "5173:5173"
    volumes:
      - ./front-end/geobrasil:/app
    environment:
      - NODE_ENV=development
